#!/usr/bin/env python3
"""repro-web 任务注册 + nginx 配置生成 + 热 reload。

用法:
  register.py add <task_id> <port> <name> [--framework nextjs|fastapi|streamlit|gradio|generic] [--rule 'a=b']...
  register.py rm <task_id>
  register.py gen                          # 仅按 tasks.json 重新生成并 reload
  register.py status                       # 列出已注册任务与存活端口

每次写操作都会: 更新 tasks.json -> 重新生成 nginx/tasks.conf -> nginx -t -> HUP 热重载。
nginx 常驻 8080, 任务端口只绑 127.0.0.1, 全程不需要发布端口/重启容器。
"""
import argparse
import json
import os
import signal
import socket
import subprocess
import sys

D = "/workspace/.repro-web"
NGX_CONF = f"{D}/nginx/nginx.conf"
TASKS_CONF = f"{D}/nginx/tasks.conf"
TASKS_JSON = f"{D}/tasks.json"
# 浏览器可见前缀(经 ASIS /insights -> ai4sec /repro-web -> 本 nginx /task/{id})
PREFIX = "/insights/repro-web/task"

# 通用规则: base href 注入 + Next.js 静态资源路径。
# 注意 {prefix} 本身以 / 开头, 格式串里不要在其前再写斜杠。
BASE_RULES = [
    ("</head>", '<base href="{prefix}/"></head>'),
    ('="/_next/', '="{prefix}/_next/'),
    ('"/_next/', '"{prefix}/_next/'),
]

# 按框架的附加改写规则
FRAMEWORK_RULES = {
    "nextjs": [
        ('="/api/', '="{prefix}/api/'),
        ('"/api/', '"{prefix}/api/'),
        ("'/api/", "'{prefix}/api/"),
        ('="/ws', '="{prefix}/ws'),
        ('"/ws', '"{prefix}/ws'),
        ("'/ws", "'{prefix}/ws"),
    ],
    "fastapi": [
        ('="/api/', '="{prefix}/api/'),
        ('"/api/', '"{prefix}/api/'),
        ("'/api/", "'{prefix}/api/"),
    ],
    "streamlit": [
        ('="/static/', '="{prefix}/static/'),
        ('"/static/', '"{prefix}/static/'),
        ("'/static/", "'{prefix}/static/"),
        ('="/_stcore/', '="{prefix}/_stcore/'),
        ('"/_stcore/', '"{prefix}/_stcore/'),
        ("'/_stcore/", "'{prefix}/_stcore/"),
        ('="/favicon.ico', '="{prefix}/favicon.ico'),
    ],
    "gradio": [
        ('="/gradio_api/', '="{prefix}/gradio_api/'),
        ('"/gradio_api/', '"{prefix}/gradio_api/'),
        ('="/gradio/', '="{prefix}/gradio/'),
        ('"/gradio/', '"{prefix}/gradio/'),
    ],
    "generic": [],
}


def load_tasks() -> dict:
    if os.path.exists(TASKS_JSON):
        try:
            return json.load(open(TASKS_JSON))
        except Exception:
            pass
    return {"tasks": {}}


def save_tasks(tasks: dict) -> None:
    tmp = TASKS_JSON + ".tmp"
    with open(tmp, "w") as f:
        json.dump(tasks, f, ensure_ascii=False, indent=2)
    os.replace(tmp, TASKS_JSON)


def _q(s: str) -> str:
    """nginx 参数引号: 含单引号用双引号包, 否则单引号包。"""
    if "'" in s:
        return f'"{s}"'
    return f"'{s}'"


def gen_location(tid: str, t: dict) -> str:
    """生成任务的分发配置: 写 per-task .inc(共享代理/改写设置), 返回两个 location。

    location = /task/{id}   精确匹配无斜杠路径(ASIS 308 剥尾斜杠后会走到这),
                           直接分发到应用根, 避免 nginx 自动 301 补斜杠时用内部 Host
                           生成不可访问的绝对 Location(http://repro:8080/...)。
    location /task/{id}/    前缀匹配所有子路径(含静态资源/API/WS)。
    """
    port = t.get("port")
    if not port:
        return ""
    prefix = f"{PREFIX}/{tid}"
    framework = t.get("framework", "generic")
    name = t.get("name", f"task-{tid}")
    rules = list(BASE_RULES) + list(FRAMEWORK_RULES.get(framework, []))
    extra = t.get("rules") or []
    for e in extra:
        if "=" in e:
            a, b = e.split("=", 1)
            rules.append((a, b))
    inc_lines = [
        f"    proxy_pass http://127.0.0.1:{port}/;",
        "    proxy_http_version 1.1;",
        "    proxy_set_header Host $host;",
        "    proxy_set_header X-Real-IP $remote_addr;",
        "    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
        "    proxy_set_header X-Forwarded-Proto $scheme;",
        "    proxy_set_header Upgrade $http_upgrade;",
        "    proxy_set_header Connection $connection_upgrade;",
        "    proxy_set_header Accept-Encoding \"\";",
        "    proxy_read_timeout 300s;",
        "    proxy_send_timeout 300s;",
        # text/html 是 nginx 默认 sub_filter_type, 显式再列会因同一 inc 被两个 location include 两次
        # 而报 "duplicate MIME type text/html"(无害但每次 reload 刷警告); 只列非默认类型。
        # nextjs 静态导出的 .js 被 uvicorn 以 text/javascript 下发(sub_filter_types 未列则不改写),
        # 否则 JS 内 fetch("/api/...") 保持根相对路径 → 打到 ASIS 入口(Next.js)而非 repro 总机 → 401。
        # 只给 nextjs 加此类型; streamlit/gradio 的 JS 不应被 /api /ws 改写。
        f"    sub_filter_types text/css application/javascript application/x-javascript image/svg+xml{' text/javascript' if framework == 'nextjs' else ''};",
        "    sub_filter_once off;",
    ]
    for a, b in rules:
        inc_lines.append(f"    sub_filter {_q(a)} {_q(b.format(prefix=prefix))};")
    inc = f"{D}/nginx/task-{tid}.inc"
    with open(inc + ".tmp", "w") as f:
        f.write("# auto-generated by register.py; do not edit\n")
        f.write("\n".join(inc_lines) + "\n")
    os.replace(inc + ".tmp", inc)
    return (
        f"# [task {tid}] {name} (framework={framework}, port={port})\n"
        f"location = /task/{tid} {{ include {inc}; }}\n"
        f"location /task/{tid}/ {{ include {inc}; }}\n"
    )


def gen_tasks_conf() -> None:
    tasks = load_tasks().get("tasks", {})
    blocks = []
    for tid in sorted(tasks, key=lambda x: (int(x) if str(x).isdigit() else x)):
        blocks.append(gen_location(str(tid), tasks[tid]))
    tmp = TASKS_CONF + ".tmp"
    with open(tmp, "w") as f:
        f.write("# auto-generated by register.py; do not edit\n")
        f.write("".join(blocks))
    os.replace(tmp, TASKS_CONF)


def reload_nginx() -> bool:
    r = subprocess.run(["nginx", "-t", "-c", NGX_CONF], capture_output=True, text=True)
    if r.returncode != 0:
        print("nginx -t FAILED:\n" + (r.stdout + r.stderr), file=sys.stderr)
        return False
    pid_file = f"{D}/nginx/nginx.pid"
    if os.path.exists(pid_file):
        try:
            with open(pid_file) as f:
                os.kill(int(f.read().strip()), signal.SIGHUP)
        except (ValueError, ProcessLookupError):
            print("nginx master not running; config regenerated, start nginx manually", file=sys.stderr)
            return False
    return True


def _port_alive(port: int) -> bool:
    s = socket.socket()
    s.settimeout(1)
    try:
        return s.connect_ex(("127.0.0.1", port)) == 0
    finally:
        s.close()


def cmd_add(args) -> int:
    tasks = load_tasks()
    tid = str(args.task_id)
    tasks.setdefault("tasks", {})[tid] = {
        "name": args.name,
        "port": int(args.port),
        "framework": args.framework,
        "launch": f"task-{tid}.sh",
        "rules": args.rule or [],
    }
    save_tasks(tasks)
    gen_tasks_conf()
    ok = reload_nginx()
    print(f"task#{tid} registered -> 127.0.0.1:{args.port} ({args.name}, {args.framework})")
    return 0 if ok else 1


def cmd_rm(args) -> int:
    tasks = load_tasks()
    tid = str(args.task_id)
    if tasks.get("tasks", {}).pop(tid, None) is None:
        print(f"task#{tid} not registered")
        return 1
    save_tasks(tasks)
    gen_tasks_conf()
    ok = reload_nginx()
    print(f"task#{tid} removed")
    return 0 if ok else 1


def cmd_gen(_args) -> int:
    gen_tasks_conf()
    ok = reload_nginx()
    print(f"tasks.conf regenerated ({len(load_tasks().get('tasks', {}))} tasks)")
    return 0 if ok else 1


def cmd_status(_args) -> int:
    tasks = load_tasks().get("tasks", {})
    if not tasks:
        print("no tasks registered")
        return 0
    for tid in sorted(tasks, key=lambda x: (int(x) if str(x).isdigit() else x)):
        t = tasks[tid]
        alive = _port_alive(t["port"])
        print(
            f"task#{tid} {t.get('name', ''):20s} port={t['port']} "
            f"alive={'YES' if alive else 'no '} framework={t.get('framework', 'generic')}"
        )
    return 0


def main() -> int:
    p = argparse.ArgumentParser(prog="register.py")
    sub = p.add_subparsers(dest="cmd", required=True)
    pa = sub.add_parser("add", help="注册/更新一个任务")
    pa.add_argument("task_id", type=int)
    pa.add_argument("port", type=int)
    pa.add_argument("name")
    pa.add_argument("--framework", default="generic",
                    choices=["nextjs", "fastapi", "streamlit", "gradio", "generic"])
    pa.add_argument("--rule", action="append", default=[], help="附加改写规则 'a=b'")
    pa.set_defaults(func=cmd_add)
    pr = sub.add_parser("rm", help="移除一个任务")
    pr.add_argument("task_id", type=int)
    pr.set_defaults(func=cmd_rm)
    pg = sub.add_parser("gen", help="按 tasks.json 重新生成并 reload")
    pg.set_defaults(func=cmd_gen)
    ps = sub.add_parser("status", help="列出任务与存活状态")
    ps.set_defaults(func=cmd_status)
    args = p.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
