/**
 * threatStaticData — v12 demo static fallback data.
 *
 * These structures are v12-specific and NOT provided by the v9 backend contract.
 * Used by threatAdapters.ts as fallback when contract doesn't provide these fields.
 *
 * Every fallback is clearly commented. When the contract later provides these fields,
 * the adapter will prefer contract data over these static values.
 *
 * Source: demo/index-v12.html (lines 5423-5537)
 */

import type {
  ThreatSurfaceDetail,
} from '../../types/threat';

// ============================================================================
// surfaces — attack surface aggregate stats (demo v12 lines 5423-5430)
// Contract's attackSurface.data.report has by_grade but not per-surface breakdown.
// Used by ThreatSurface view (W3.2) for the surface matrix.
// ============================================================================
export const surfaces: ThreatSurfaceDetail[] = [
  {
    id: 'kernel',
    title: 'kernel',
    count: 128,
    demoCount: 1,
    top: 'openharmony/kernel_linux_4.19',
    score: 87,
    cves: 412,
    secItems: 530,
    gradeA: 28,
    assets: 12,
    icon: 'K',
    desc: '内核、驱动边界、系统调用和补丁链路。',
    purpose:
      '不是列仓库，而是把内核/驱动类目标整理成一条挖洞路径：补丁 diff → 驱动入口 → 权限边界 → variant hunting。',
    paths: ['CVE 补丁 diff 聚类', 'ioctl 参数边界审计', '驱动权限检查缺失', '文件系统/网络栈历史补丁变体'],
    evidence: ['历史 CVE 6+ 条', 'security-disclosure 补丁链路', 'OpenHarmony / openEuler 内核维护分支'],
    hypotheses: ['相似驱动分支未同步补丁', '权限检查 TOCTOU', 'copy_from_user 边界遗漏'],
  },
  {
    id: 'network protocol',
    title: 'network protocol',
    count: 214,
    demoCount: 2,
    top: 'Cangjie/cangjie_stdx',
    score: 85,
    cves: 76,
    secItems: 188,
    gradeA: 42,
    assets: 9,
    icon: 'N',
    desc: '协议解析、编码、TLS/curl 传输链路。',
    purpose:
      '聚合网络协议、URL 编解码、HTTP client、TLS/curl 适配等输入解析路径，形成协议层审计清单。',
    paths: ['URL percent-encoding 差异', 'HTTP header / request-target 规范化', 'TLS/证书校验默认值', '代理/VPN 配置注入'],
    evidence: ['Cangjie stdx HTTP client issue', 'openHiTLS curl 国密适配', 'NetManager VPN/proxy 线索'],
    hypotheses: ['请求走私/路径混淆', '证书校验绕过', '代理配置越权'],
  },
  {
    id: 'database',
    title: 'database',
    count: 46,
    demoCount: 1,
    top: 'opengauss/security',
    score: 83,
    cves: 273,
    secItems: 318,
    gradeA: 11,
    assets: 3,
    icon: 'D',
    desc: '数据库安全公告、依赖和服务端攻击面。',
    purpose: '把数据库安全公告、依赖和服务端攻击面汇总成复核入口，适合公告去重和补丁模式归纳。',
    paths: ['CVE/SA 公告去重', '补丁文件定位', '依赖组件版本差异', '服务端权限边界'],
    evidence: ['openGauss security repo', '273 个 CVE/SA 线索'],
    hypotheses: ['补丁变体漏洞', '默认配置风险', '依赖版本漂移'],
  },
  {
    id: 'driver',
    title: 'driver',
    count: 96,
    demoCount: 1,
    top: 'Ascend/ascend-deployer',
    score: 78,
    cves: 23,
    secItems: 96,
    gradeA: 15,
    assets: 18,
    icon: 'R',
    desc: '驱动安装、部署工具、镜像配置和权限。',
    purpose: '聚焦部署、驱动安装、设备权限和镜像配置链路，不再只看仓库分数。',
    paths: ['安装脚本输入校验', '驱动权限/设备节点', '镜像配置和环境变量', '固件包版本漂移'],
    evidence: ['Ascend deployer issue', 'Atlas HDK 固件资产', 'MindIE 镜像弱关联'],
    hypotheses: ['权限提升', '配置注入', '供应链包替换'],
  },
  {
    id: 'parser/codec',
    title: 'parser/codec',
    count: 83,
    demoCount: 1,
    top: 'cann/ge',
    score: 77,
    cves: 8,
    secItems: 67,
    gradeA: 9,
    assets: 7,
    icon: 'P',
    desc: '模型格式解析、图编译、二进制/结构化输入。',
    purpose: '把模型格式、图编译、二进制结构化输入解析集中看，适合 fuzzing 和格式解析审计。',
    paths: ['ONNX/PB 模型解析', '图编译执行链路', '类型/shape 边界', '序列化/反序列化'],
    evidence: ['cann/ge Graph Engine', '模型格式解析入口'],
    hypotheses: ['解析 OOB', '类型混淆', 'shape 整数溢出'],
  },
  {
    id: 'exec/permission',
    title: 'exec/permission',
    count: 176,
    demoCount: 2,
    top: 'openUBMC/account',
    score: 78,
    cves: 31,
    secItems: 144,
    gradeA: 24,
    assets: 5,
    icon: 'E',
    desc: '权限、账号、沙箱和安全边界。',
    purpose: '聚合账号、权限、AccessToken、SELinux/策略类边界，服务越权和策略绕过审计。',
    paths: ['账号权限变更', 'AccessToken 校验路径', '策略 allow 规则漂移', '服务间调用边界'],
    evidence: ['openUBMC account', 'security_access_token', 'SELinux 策略变更'],
    hypotheses: ['越权访问', '策略过宽', '服务权限错配'],
  },
  {
    id: 'sandbox',
    title: 'sandbox',
    count: 0, demoCount: 0, top: '', score: 0, cves: 0, secItems: 0, gradeA: 0, assets: 0,
    icon: 'S', desc: '容器、沙箱、隔离机制和安全边界。',
    purpose: '聚焦容器/沙箱/隔离机制的安全边界审计，关注逃逸和越权。',
    paths: ['沙箱逃逸路径', '容器隔离突破', '命名空间权限', 'capability 滥用'],
    evidence: ['Docker/containerd 历史逃逸', 'Linux namespace 漏洞'],
    hypotheses: ['沙箱逃逸', '容器越权', 'capability 提权'],
  },
  {
    id: 'wireless',
    title: 'wireless',
    count: 0, demoCount: 0, top: '', score: 0, cves: 0, secItems: 0, gradeA: 0, assets: 0,
    icon: 'W', desc: '蓝牙、WiFi、NFC、NearLink 等无线协议。',
    purpose: '聚合蓝牙、WiFi、NFC、NearLink 等无线协议的安全审计路径。',
    paths: ['协议栈实现审计', '配对/认证流程', '中间人攻击防御', '固件无线模块漏洞'],
    evidence: ['蓝牙协议历史漏洞', 'WiFi WPA 漏洞链路'],
    hypotheses: ['配对流程绕过', '协议栈解析溢出', '中间人攻击'],
  },
  {
    id: 'peripheral',
    title: 'peripheral',
    count: 0, demoCount: 0, top: '', score: 0, cves: 0, secItems: 0, gradeA: 0, assets: 0,
    icon: 'U', desc: 'USB、HID、UART、I2C、SPI、GPIO 等外设接口。',
    purpose: '聚焦 USB/HID/UART/I2C/SPI/GPIO 等外设接口的安全边界审计。',
    paths: ['USB 描述符解析', 'HID 报告注入', 'UART 调试接口暴露', 'I2C/SPI 设备权限'],
    evidence: ['USB 协议历史漏洞', 'HID 攻击工具链'],
    hypotheses: ['恶意设备注入', '调试接口越权', '外设驱动溢出'],
  },
  {
    id: 'media',
    title: 'media',
    count: 0, demoCount: 0, top: '', score: 0, cves: 0, secItems: 0, gradeA: 0, assets: 0,
    icon: 'M', desc: '摄像头、视频编解码、音频处理等媒体处理链路。',
    purpose: '聚焦摄像头、视频编解码、音频处理等媒体处理链路的安全审计。',
    paths: ['视频编解码器 fuzzing', '摄像头 V4L2 接口', '音频处理溢出', '容器格式解析'],
    evidence: ['H.264/H.265 历史漏洞', 'FFmpeg 漏洞链路'],
    hypotheses: ['编解码器内存损坏', '容器格式混淆', '摄像头权限越权'],
  },
  {
    id: 'browser engine',
    title: 'browser engine',
    count: 0, demoCount: 0, top: '', score: 0, cves: 0, secItems: 0, gradeA: 0, assets: 0,
    icon: 'B', desc: 'Chromium、WebKit、V8、Skia、Blink 等浏览器引擎。',
    purpose: '聚焦 Chromium/WebKit/V8/Skia/Blink 等浏览器引擎的安全审计。',
    paths: ['JS 引擎 JIT 漏洞', '渲染管线溢出', 'Web API 越权', '沙箱逃逸'],
    evidence: ['Chromium 历史高危 CVE', 'V8 JIT 漏洞链路'],
    hypotheses: ['JIT 类型混淆', '渲染越界读写', '沙箱逃逸链'],
  },
];

// ============================================================================
// ecosystemSecondLevel — 28 Huawei open-source ecosystem orgs (demo v12 lines 5513-5522)
// Used by W2.3 buildDualTreeGraph for the second-level nodes in the dual-root tree.
// Contract does not provide this ecosystem taxonomy.
// ============================================================================
export const ecosystemSecondLevel: Array<[string, string]> = [
  ['Ascend', 'Ascend (昇腾AI)'],
  ['Cangjie', '仓颉 (编程语言)'],
  ['Cantian', 'Cantian (数据库)'],
  ['DevCloudFE', 'DevCloudFE (前端)'],
  ['ModelEngine', 'ModelEngine (模型引擎)'],
  ['arkui-x', 'arkui-x'],
  ['cann', 'CANN (计算架构)'],
  ['eBackup', 'eBackup (备份)'],
  ['huaweicloud', '华为云'],
  ['kappital', 'Kappital'],
  ['kunpengcompute', '鲲鹏计算'],
  ['mindspore', 'MindSpore (AI框架)'],
  ['openFuyao', 'openFuyao'],
  ['openHiTLS', 'openHiTLS (密码库)'],
  ['openInula', 'openInula (前端框架)'],
  ['openJiuwen', 'openJiuwen (AI Agent)'],
  ['openUBMC', 'openUBMC (运维)'],
  ['openeuler', 'openEuler (操作系统)'],
  ['opengauss', 'openGauss (数据库)'],
  ['openharmony', 'OpenHarmony (鸿蒙内核)'],
  ['openharmony-sig', 'OpenHarmony SIG (特别兴趣组)'],
  ['openharmony-tpc', 'OpenHarmony TPC (三方组件)'],
  ['openkylin', 'openKylin'],
  ['openlookeng', 'openLooKeng (大数据)'],
  ['opentiny', 'OpenTiny (前端组件)'],
  ['Ascend_FW_Community', '昇腾固件(社区版)'],
  ['Ascend_FW_Commercial', '昇腾固件(商业版)'],
  ['AscendHub', 'AscendHub镜像仓库'],
  ['Huawei_Mirrors', '华为开源镜像站'],
  ['OpenX_Huawei', 'OpenX华为设备固件'],
];
